// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recipe struct {
	ID           int32
	Ingredients  pgtype.Text
	Instructions pgtype.Text
}

type RecipeFollow struct {
	ID       int32
	RecipeID int32
	UserID   int32
}

type RefreshToken struct {
	Token      string
	ValidFrom  pgtype.Timestamp
	ValidUntil pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
	UserID     int32
}

type User struct {
	ID       int32
	Username pgtype.Text
	Password pgtype.Text
}
