// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Recipe struct {
	ID           int32
	UserID       int32
	Ingredients  sql.NullString
	Instructions sql.NullString
}

type User struct {
	ID       int32
	Username sql.NullString
	Password sql.NullString
}
