// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recipe.sql

package database

import (
	"context"
)

const deleteRecipeById = `-- name: DeleteRecipeById :one
DELETE FROM recipes
WHERE id = $1
RETURNING id, ingredients, instructions
`

func (q *Queries) DeleteRecipeById(ctx context.Context, id int32) (Recipe, error) {
	row := q.db.QueryRow(ctx, deleteRecipeById, id)
	var i Recipe
	err := row.Scan(&i.ID, &i.Ingredients, &i.Instructions)
	return i, err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, ingredients, instructions FROM recipes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecipeByID(ctx context.Context, id int32) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(&i.ID, &i.Ingredients, &i.Instructions)
	return i, err
}
